name: lumalearn
description: AI-guided learning application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
              flutter:
                sdk: flutter

  # --- Architecture & State ---
              flutter_riverpod: ^2.5.1
              riverpod_annotation: ^2.3.5
              go_router: ^14.0.0  # [cite: 13]

  # --- Backend ---
              supabase_flutter: ^2.6.0 # [cite: 14, 60]

  # --- UI & Utilities ---
              google_fonts: ^6.2.1
              flutter_markdown: ^0.7.1 # For rendering AI hints [cite: 13]
              flutter_tex: ^4.0.0

              flutter_svg: ^2.0.10
              glassmorphism: ^3.0.0 # To achieve the glass effect in the design
              intl: ^0.20.2
              cupertino_icons: ^1.0.8
              http: ^1.6.0
              uuid: ^4.5.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_lumalearn.png"
  min_sdk_android: 21 # optional
  # adaptive_icon_background: "#0A0A0A" # Optional: Matches your dark background
  # adaptive_icon_foreground: "assets/icons/app_logo.png" # Optional: For newer Android versions
